server:
  port: 8099

spring:
  application:
    name: capstone-enterprise-ai-assistant
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
