server:
  port: 8092

spring:
  application:
    name: module-12-production-native-aot
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
