server:
  port: 8091

spring:
  application:
    name: module-11-security-and-observability
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
