package com.springai.edu.module01.dto;

/**
 * Standard response payload returned after ChatClient execution.
 *
 * @param content          The text output generated by the LLM
 * @param modelUsed        The identifier of the model that served the request
 * @param promptTokens     Estimated or reported prompt token count
 * @param generationTokens Estimated or reported output token count
 * @param durationMs       Total roundtrip duration in milliseconds
 */
public record ChatPromptResponse(
        String content,
        String modelUsed,
        long promptTokens,
        long generationTokens,
        long durationMs
) {}
